-- First real keystone_questions content, staged for review per Iman's
-- explicit call: "staged as pending/unverified for review, like UTME's
-- approach" -- not straight to approved. Every row here has
-- approval_status='pending', so none of it surfaces in Quick Test
-- (which filters approval_status='approved') until an admin reviews
-- and approves it.
--
-- Scope: one representative course per priority faculty (breadth over
-- depth, matching the original course-catalog request's shape) --
-- Anatomy I (Medicine), Pharmacology I (Pharmacy), Anatomy for Nursing,
-- Nigerian Legal System (Law), Engineering Mathematics I (the Civil
-- Engineering instance of the shared common-core course), GST101 Use
-- of English (General Studies), and Principles of Toxicology
-- (Environmental Management and Toxicology). 8 questions each, 56
-- total. Every other course populated in migrations 0007-0009 still
-- has zero questions -- this is a first pass, not claimed coverage.
--
-- No dedicated review-note column exists on keystone_questions yet
-- (checked before writing this) -- provenance is prefixed into each
-- row's explanation as "[PENDING REVIEW]" so a reviewer sees it during
-- approval; a real review_note column, separate from the student-facing
-- explanation, is a clean follow-up schema improvement, not done here.
--
-- Content itself: drawn from standard, uncontroversial, textbook-level
-- facts in each field (basic human anatomy, foundational pharmacology
-- mechanisms, well-documented Nigerian constitutional/legal structure,
-- standard calculus/algebra, English grammar fundamentals, core
-- toxicology definitions) -- chosen deliberately to minimize factual-
-- error risk at a first pass, not cutting-edge or disputed material in
-- any field. Still needs real subject-matter review before approval,
-- same as any AI-originated content would.

insert into cgpa.keystone_questions (course_id, cognitive_patterns, information_types, prompt, options, correct_option_id, explanation, difficulty, source, approval_status) values

-- Anatomy I (Medicine, course_id=39)
(39, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The femur is the principal bone of which region of the body?', '[{"id":"a","text":"Thigh"},{"id":"b","text":"Forearm"},{"id":"c","text":"Lower leg"},{"id":"d","text":"Upper arm"}]'::jsonb, 'a', '[PENDING REVIEW] The femur is the longest and strongest bone in the human body, located in the thigh, articulating with the pelvis at the hip and the tibia/patella at the knee.', 1, 'standard', 'pending'),
(39, ARRAY['Logical'], ARRAY['Essential / definitive'], 'How many bones are in the adult human skeleton?', '[{"id":"a","text":"186"},{"id":"b","text":"196"},{"id":"c","text":"206"},{"id":"d","text":"216"}]'::jsonb, 'c', '[PENDING REVIEW] The adult human skeleton has 206 bones; infants are born with roughly 270-300, many of which fuse during growth.', 1, 'standard', 'pending'),
(39, ARRAY['Logical'], ARRAY['Essential / definitive'], 'How many chambers does the human heart have?', '[{"id":"a","text":"2"},{"id":"b","text":"3"},{"id":"c","text":"4"},{"id":"d","text":"6"}]'::jsonb, 'c', '[PENDING REVIEW] The heart has four chambers: right atrium, right ventricle, left atrium, left ventricle.', 1, 'standard', 'pending'),
(39, ARRAY['Logical'], ARRAY['Essential / definitive'], 'What is the largest organ in the human body?', '[{"id":"a","text":"Liver"},{"id":"b","text":"Skin"},{"id":"c","text":"Lungs"},{"id":"d","text":"Small intestine"}]'::jsonb, 'b', '[PENDING REVIEW] The skin is the largest organ by surface area and weight, forming the integumentary system.', 1, 'standard', 'pending'),
(39, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The spinal cord is directly protected by which structure?', '[{"id":"a","text":"Ribcage"},{"id":"b","text":"Skull"},{"id":"c","text":"Vertebral column"},{"id":"d","text":"Sternum"}]'::jsonb, 'c', '[PENDING REVIEW] The vertebral column (spine) encases and protects the spinal cord within the vertebral canal.', 1, 'standard', 'pending'),
(39, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Which cranial nerve is primarily responsible for vision?', '[{"id":"a","text":"Optic nerve (CN II)"},{"id":"b","text":"Olfactory nerve (CN I)"},{"id":"c","text":"Trigeminal nerve (CN V)"},{"id":"d","text":"Vagus nerve (CN X)"}]'::jsonb, 'a', '[PENDING REVIEW] The optic nerve (cranial nerve II) transmits visual information from the retina to the brain.', 2, 'standard', 'pending'),
(39, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The trachea bifurcates into which two structures?', '[{"id":"a","text":"Left and right bronchi"},{"id":"b","text":"Left and right lungs"},{"id":"c","text":"Alveoli and bronchioles"},{"id":"d","text":"Larynx and pharynx"}]'::jsonb, 'a', '[PENDING REVIEW] The trachea splits at the carina into the left and right main bronchi, each entering a lung.', 2, 'standard', 'pending'),
(39, ARRAY['Logical'], ARRAY['Essential / definitive'], 'What is the functional unit of the kidney called?', '[{"id":"a","text":"Nephron"},{"id":"b","text":"Alveolus"},{"id":"c","text":"Neuron"},{"id":"d","text":"Villus"}]'::jsonb, 'a', '[PENDING REVIEW] The nephron is the basic structural and functional unit of the kidney, responsible for filtering blood and forming urine.', 2, 'standard', 'pending'),

-- Pharmacology I (Pharmacy, course_id=160)
(160, ARRAY['Logical'], ARRAY['Essential / definitive'], 'ED50 refers to the dose that produces:', '[{"id":"a","text":"A lethal effect in 50% of a population"}, {"id":"b","text":"50% of the maximal therapeutic effect in 50% of a population"}, {"id":"c","text":"Toxicity in all subjects"}, {"id":"d","text":"No measurable effect"}]'::jsonb, 'b', '[PENDING REVIEW] ED50 (median effective dose) is the dose producing a specified effect (often 50% of maximal response) in 50% of the population tested.', 3, 'standard', 'pending'),
(160, ARRAY['Logical'], ARRAY['Essential / definitive'], 'First-pass metabolism of orally administered drugs primarily occurs in the:', '[{"id":"a","text":"Kidney"}, {"id":"b","text":"Liver"}, {"id":"c","text":"Lungs"}, {"id":"d","text":"Stomach"}]'::jsonb, 'b', '[PENDING REVIEW] The liver extensively metabolizes many orally administered drugs before they reach systemic circulation -- first-pass (hepatic) metabolism.', 2, 'standard', 'pending'),
(160, ARRAY['Logical'], ARRAY['Essential / definitive'], 'A drug that blocks beta-adrenergic receptors is classified as a:', '[{"id":"a","text":"Beta agonist"}, {"id":"b","text":"Beta blocker"}, {"id":"c","text":"Alpha blocker"}, {"id":"d","text":"Calcium channel blocker"}]'::jsonb, 'b', '[PENDING REVIEW] Beta blockers (e.g. propranolol) competitively antagonize beta-adrenergic receptors, commonly used in hypertension and arrhythmias.', 1, 'standard', 'pending'),
(160, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Which route of administration bypasses first-pass hepatic metabolism entirely?', '[{"id":"a","text":"Oral"}, {"id":"b","text":"Intravenous"}, {"id":"c","text":"Rectal (partial)"}, {"id":"d","text":"Enteric-coated oral"}]'::jsonb, 'b', '[PENDING REVIEW] Intravenous administration delivers the drug directly into systemic circulation, avoiding first-pass hepatic metabolism.', 2, 'standard', 'pending'),
(160, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Aspirin exerts its anti-inflammatory effect primarily by inhibiting which enzyme?', '[{"id":"a","text":"Cyclooxygenase (COX)"}, {"id":"b","text":"Lipoxygenase"}, {"id":"c","text":"Acetylcholinesterase"}, {"id":"d","text":"Monoamine oxidase"}]'::jsonb, 'a', '[PENDING REVIEW] Aspirin irreversibly inhibits cyclooxygenase (COX-1 and COX-2), reducing prostaglandin synthesis.', 2, 'standard', 'pending'),
(160, ARRAY['Logical'], ARRAY['Essential / definitive'], 'A drug that competes with an agonist for the same receptor binding site, without activating it, is called a:', '[{"id":"a","text":"Competitive antagonist"}, {"id":"b","text":"Non-competitive antagonist"}, {"id":"c","text":"Partial agonist"}, {"id":"d","text":"Inverse agonist"}]'::jsonb, 'a', '[PENDING REVIEW] A competitive antagonist binds reversibly to the same site as the agonist, and its effect can be overcome by increasing agonist concentration.', 3, 'standard', 'pending'),
(160, ARRAY['Logical'], ARRAY['Essential / definitive'], 'ACE inhibitors are primarily used in the treatment of:', '[{"id":"a","text":"Hypertension"}, {"id":"b","text":"Diabetes mellitus"}, {"id":"c","text":"Asthma"}, {"id":"d","text":"Peptic ulcer disease"}]'::jsonb, 'a', '[PENDING REVIEW] ACE inhibitors block angiotensin-converting enzyme, reducing angiotensin II formation, widely used as antihypertensives.', 1, 'standard', 'pending'),
(160, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The time required for the plasma concentration of a drug to reduce by half is called its:', '[{"id":"a","text":"Onset of action"}, {"id":"b","text":"Half-life"}, {"id":"c","text":"Bioavailability"}, {"id":"d","text":"Therapeutic index"}]'::jsonb, 'b', '[PENDING REVIEW] Half-life (t1/2) is the time for plasma drug concentration to fall by 50%, a key determinant of dosing frequency.', 2, 'standard', 'pending'),

-- Anatomy for Nursing (course_id=168)
(168, ARRAY['Logical'], ARRAY['Essential / definitive'], 'How many chambers does the human heart have?', '[{"id":"a","text":"2"}, {"id":"b","text":"3"}, {"id":"c","text":"4"}, {"id":"d","text":"6"}]'::jsonb, 'c', '[PENDING REVIEW] The heart has four chambers: two atria and two ventricles.', 1, 'standard', 'pending'),
(168, ARRAY['Logical'], ARRAY['Essential / definitive'], 'What is the largest artery in the human body?', '[{"id":"a","text":"Pulmonary artery"}, {"id":"b","text":"Aorta"}, {"id":"c","text":"Carotid artery"}, {"id":"d","text":"Femoral artery"}]'::jsonb, 'b', '[PENDING REVIEW] The aorta is the largest artery, carrying oxygenated blood from the left ventricle to the rest of the body.', 1, 'standard', 'pending'),
(168, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The functional unit of the kidney is the:', '[{"id":"a","text":"Nephron"}, {"id":"b","text":"Alveolus"}, {"id":"c","text":"Villus"}, {"id":"d","text":"Neuron"}]'::jsonb, 'a', '[PENDING REVIEW] The nephron filters blood and forms urine; each kidney contains roughly a million nephrons.', 2, 'standard', 'pending'),
(168, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Which bone forms the kneecap?', '[{"id":"a","text":"Femur"}, {"id":"b","text":"Patella"}, {"id":"c","text":"Tibia"}, {"id":"d","text":"Fibula"}]'::jsonb, 'b', '[PENDING REVIEW] The patella (kneecap) is a sesamoid bone embedded in the quadriceps tendon.', 1, 'standard', 'pending'),
(168, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Which gland primarily regulates the body''s metabolic rate?', '[{"id":"a","text":"Adrenal gland"}, {"id":"b","text":"Thyroid gland"}, {"id":"c","text":"Pituitary gland"}, {"id":"d","text":"Pancreas"}]'::jsonb, 'b', '[PENDING REVIEW] The thyroid gland secretes T3 and T4, which regulate the body''s basal metabolic rate.', 2, 'standard', 'pending'),
(168, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The outer layer of the brain is known as the:', '[{"id":"a","text":"Cerebral cortex"}, {"id":"b","text":"Cerebellum"}, {"id":"c","text":"Medulla oblongata"}, {"id":"d","text":"Hypothalamus"}]'::jsonb, 'a', '[PENDING REVIEW] The cerebral cortex is the outer layer of grey matter responsible for higher-order functions.', 2, 'standard', 'pending'),
(168, ARRAY['Logical'], ARRAY['Essential / definitive'], 'How many pairs of ribs does the human body typically have?', '[{"id":"a","text":"10"}, {"id":"b","text":"11"}, {"id":"c","text":"12"}, {"id":"d","text":"14"}]'::jsonb, 'c', '[PENDING REVIEW] Humans typically have 12 pairs of ribs, forming the ribcage that protects the heart and lungs.', 1, 'standard', 'pending'),
(168, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Which organ produces insulin?', '[{"id":"a","text":"Liver"}, {"id":"b","text":"Pancreas"}, {"id":"c","text":"Spleen"}, {"id":"d","text":"Gallbladder"}]'::jsonb, 'b', '[PENDING REVIEW] The pancreas produces insulin via its beta cells in the islets of Langerhans.', 1, 'standard', 'pending'),

-- Nigerian Legal System (Law, course_id=24)
(24, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The Nigerian legal system is primarily based on which legal tradition?', '[{"id":"a","text":"English common law"}, {"id":"b","text":"French civil law"}, {"id":"c","text":"Roman-Dutch law"}, {"id":"d","text":"Sharia law exclusively"}]'::jsonb, 'a', '[PENDING REVIEW] Nigeria''s legal system is rooted in English common law, inherited through colonial history, alongside customary and Islamic law in various contexts.', 1, 'standard', 'pending'),
(24, ARRAY['Logical'], ARRAY['Essential / definitive'], 'What is the highest court in Nigeria?', '[{"id":"a","text":"Court of Appeal"}, {"id":"b","text":"Federal High Court"}, {"id":"c","text":"Supreme Court"}, {"id":"d","text":"State High Court"}]'::jsonb, 'c', '[PENDING REVIEW] The Supreme Court of Nigeria is the apex court, with final appellate jurisdiction.', 1, 'standard', 'pending'),
(24, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The supreme law of the Federal Republic of Nigeria is the:', '[{"id":"a","text":"Criminal Code"}, {"id":"b","text":"1999 Constitution (as amended)"}, {"id":"c","text":"Evidence Act"}, {"id":"d","text":"Interpretation Act"}]'::jsonb, 'b', '[PENDING REVIEW] The 1999 Constitution (as amended) is the supreme law of Nigeria; all other laws must conform to it.', 1, 'standard', 'pending'),
(24, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Which legal system operates alongside common law in parts of Northern Nigeria?', '[{"id":"a","text":"Sharia law"}, {"id":"b","text":"Roman law"}, {"id":"c","text":"Napoleonic code"}, {"id":"d","text":"Talmudic law"}]'::jsonb, 'a', '[PENDING REVIEW] Several northern Nigerian states apply Sharia law for personal and, in some cases, criminal matters alongside the general common-law framework.', 2, 'standard', 'pending'),
(24, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Original jurisdiction over most civil matters at the state level lies with the:', '[{"id":"a","text":"Magistrate Court"}, {"id":"b","text":"State High Court"}, {"id":"c","text":"Court of Appeal"}, {"id":"d","text":"Supreme Court"}]'::jsonb, 'b', '[PENDING REVIEW] The State High Court has unlimited original jurisdiction over civil and criminal matters within the state, subject to constitutional exceptions.', 2, 'standard', 'pending'),
(24, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Customary law in Nigeria is best described as:', '[{"id":"a","text":"Written law passed by the National Assembly"}, {"id":"b","text":"Unwritten law based on the customs and traditions of a community"}, {"id":"c","text":"Law derived exclusively from religious texts"}, {"id":"d","text":"International treaty law"}]'::jsonb, 'b', '[PENDING REVIEW] Customary law is largely unwritten, deriving from the accepted customs and traditions of specific communities, and is recognized subject to compatibility with statute and public policy.', 2, 'standard', 'pending'),
(24, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The doctrine that lower courts are bound by the decisions of higher courts is known as:', '[{"id":"a","text":"Stare decisis"}, {"id":"b","text":"Habeas corpus"}, {"id":"c","text":"Mens rea"}, {"id":"d","text":"Ratio legis"}]'::jsonb, 'a', '[PENDING REVIEW] Stare decisis (judicial precedent) requires courts to follow the legal principles established by higher courts in earlier decisions.', 2, 'standard', 'pending'),
(24, ARRAY['Logical'], ARRAY['Essential / definitive'], 'At the federal level, laws are made by the:', '[{"id":"a","text":"National Assembly"}, {"id":"b","text":"Federal Executive Council"}, {"id":"c","text":"Supreme Court"}, {"id":"d","text":"Council of State"}]'::jsonb, 'a', '[PENDING REVIEW] The National Assembly (Senate and House of Representatives) holds federal legislative power under the 1999 Constitution.', 1, 'standard', 'pending'),

-- Engineering Mathematics I (Civil Engineering instance, course_id=9)
(9, ARRAY['Pure Mathematical'], ARRAY['Computation (skill)'], 'What is the derivative of x² with respect to x?', '[{"id":"a","text":"x"}, {"id":"b","text":"2x"}, {"id":"c","text":"x²"}, {"id":"d","text":"2"}]'::jsonb, 'b', '[PENDING REVIEW] Using the power rule, d/dx(x^n) = n*x^(n-1), so d/dx(x²) = 2x.', 1, 'standard', 'pending'),
(9, ARRAY['Pure Mathematical'], ARRAY['Computation (skill)'], 'What is the value of sin(90°)?', '[{"id":"a","text":"0"}, {"id":"b","text":"0.5"}, {"id":"c","text":"1"}, {"id":"d","text":"undefined"}]'::jsonb, 'c', '[PENDING REVIEW] sin(90°) = 1, the maximum value of the sine function.', 1, 'standard', 'pending'),
(9, ARRAY['Pure Mathematical'], ARRAY['Computation (skill)'], 'Solve for x: 2x + 4 = 10', '[{"id":"a","text":"x = 2"}, {"id":"b","text":"x = 3"}, {"id":"c","text":"x = 4"}, {"id":"d","text":"x = 7"}]'::jsonb, 'b', '[PENDING REVIEW] 2x + 4 = 10 -> 2x = 6 -> x = 3.', 1, 'standard', 'pending'),
(9, ARRAY['Pure Mathematical'], ARRAY['Computation (skill)'], 'The determinant of the 2x2 matrix [[a,b],[c,d]] is:', '[{"id":"a","text":"a+d - b+c"}, {"id":"b","text":"ad - bc"}, {"id":"c","text":"ab - cd"}, {"id":"d","text":"ac - bd"}]'::jsonb, 'b', '[PENDING REVIEW] For a 2x2 matrix, the determinant is calculated as (a*d) - (b*c).', 2, 'standard', 'pending'),
(9, ARRAY['Pure Mathematical'], ARRAY['Computation (skill)'], 'Evaluate the integral of 2x dx.', '[{"id":"a","text":"x + C"}, {"id":"b","text":"2x² + C"}, {"id":"c","text":"x² + C"}, {"id":"d","text":"x²/2 + C"}]'::jsonb, 'c', '[PENDING REVIEW] The integral of 2x with respect to x is x² + C, reversing the power rule of differentiation.', 2, 'standard', 'pending'),
(9, ARRAY['Pure Mathematical'], ARRAY['Computation (skill)'], 'What is the value of log10(100)?', '[{"id":"a","text":"1"}, {"id":"b","text":"2"}, {"id":"c","text":"10"}, {"id":"d","text":"100"}]'::jsonb, 'b', '[PENDING REVIEW] log10(100) = 2, since 10^2 = 100.', 1, 'standard', 'pending'),
(9, ARRAY['Pure Mathematical'], ARRAY['Computation (skill)'], 'The sum of the interior angles of a triangle is:', '[{"id":"a","text":"90°"}, {"id":"b","text":"180°"}, {"id":"c","text":"270°"}, {"id":"d","text":"360°"}]'::jsonb, 'b', '[PENDING REVIEW] The interior angles of any triangle always sum to 180°.', 1, 'standard', 'pending'),
(9, ARRAY['Pure Mathematical'], ARRAY['Computation (skill)'], 'The quadratic formula is used to solve equations of the general form:', '[{"id":"a","text":"ax + b = 0"}, {"id":"b","text":"ax² + bx + c = 0"}, {"id":"c","text":"ax³ + b = 0"}, {"id":"d","text":"a/x + b = 0"}]'::jsonb, 'b', '[PENDING REVIEW] The quadratic formula x = (-b ± sqrt(b²-4ac)) / 2a solves any equation of the form ax² + bx + c = 0.', 1, 'standard', 'pending'),

-- GST101 Use of English (course_id=183)
(183, ARRAY['Pragmatic'], ARRAY['Essential / definitive'], 'A word that names a group of things or people, such as "flock" or "committee," is called a:', '[{"id":"a","text":"Proper noun"}, {"id":"b","text":"Collective noun"}, {"id":"c","text":"Abstract noun"}, {"id":"d","text":"Compound noun"}]'::jsonb, 'b', '[PENDING REVIEW] A collective noun names a group treated as a single unit, e.g. "team," "flock," "committee."', 1, 'standard', 'pending'),
(183, ARRAY['Pragmatic'], ARRAY['Essential / definitive'], 'Which of the following is the correctly spelled word?', '[{"id":"a","text":"Definately"}, {"id":"b","text":"Definitely"}, {"id":"c","text":"Definitly"}, {"id":"d","text":"Defenitely"}]'::jsonb, 'b', '[PENDING REVIEW] "Definitely" is the correct spelling -- a commonly misspelled word.', 1, 'standard', 'pending'),
(183, ARRAY['Pragmatic'], ARRAY['Essential / definitive'], 'Which part of speech describes or modifies a verb?', '[{"id":"a","text":"Adjective"}, {"id":"b","text":"Adverb"}, {"id":"c","text":"Preposition"}, {"id":"d","text":"Conjunction"}]'::jsonb, 'b', '[PENDING REVIEW] An adverb modifies a verb, adjective, or another adverb, often describing how, when, or where an action occurs.', 1, 'standard', 'pending'),
(183, ARRAY['Pragmatic'], ARRAY['Essential / definitive'], 'At minimum, a grammatically complete sentence must contain:', '[{"id":"a","text":"A subject and a predicate"}, {"id":"b","text":"Two nouns"}, {"id":"c","text":"An adjective and a noun"}, {"id":"d","text":"A conjunction"}]'::jsonb, 'a', '[PENDING REVIEW] A complete sentence requires at minimum a subject and a predicate (verb phrase) expressing a complete thought.', 1, 'standard', 'pending'),
(183, ARRAY['Pragmatic'], ARRAY['Essential / definitive'], 'Which word is a synonym of "happy"?', '[{"id":"a","text":"Joyful"}, {"id":"b","text":"Sorrowful"}, {"id":"c","text":"Angry"}, {"id":"d","text":"Anxious"}]'::jsonb, 'a', '[PENDING REVIEW] "Joyful" shares a similar meaning to "happy," both denoting a positive emotional state.', 1, 'standard', 'pending'),
(183, ARRAY['Pragmatic'], ARRAY['Essential / definitive'], 'What is the plural form of "child"?', '[{"id":"a","text":"Childs"}, {"id":"b","text":"Childrens"}, {"id":"c","text":"Children"}, {"id":"d","text":"Childes"}]'::jsonb, 'c', '[PENDING REVIEW] "Children" is the irregular plural form of "child."', 1, 'standard', 'pending'),
(183, ARRAY['Pragmatic'], ARRAY['Essential / definitive'], 'A word that connects clauses or sentences, such as "and," "but," or "because," is called a:', '[{"id":"a","text":"Preposition"}, {"id":"b","text":"Conjunction"}, {"id":"c","text":"Pronoun"}, {"id":"d","text":"Interjection"}]'::jsonb, 'b', '[PENDING REVIEW] A conjunction joins words, phrases, or clauses, e.g. "and," "but," "because."', 1, 'standard', 'pending'),
(183, ARRAY['Pragmatic'], ARRAY['Essential / definitive'], 'Which word is an antonym of "expand"?', '[{"id":"a","text":"Enlarge"}, {"id":"b","text":"Contract"}, {"id":"c","text":"Extend"}, {"id":"d","text":"Increase"}]'::jsonb, 'b', '[PENDING REVIEW] "Contract" means to become smaller, the opposite of "expand."', 1, 'standard', 'pending'),

-- Principles of Toxicology (Environmental Management and Toxicology, course_id=194)
(194, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The founding principle of toxicology, often summarized as "the dose makes the poison," was articulated by:', '[{"id":"a","text":"Paracelsus"}, {"id":"b","text":"Louis Pasteur"}, {"id":"c","text":"Rachel Carson"}, {"id":"d","text":"Charles Darwin"}]'::jsonb, 'a', '[PENDING REVIEW] Paracelsus, a 16th-century physician, is credited with the foundational toxicological principle that any substance can be toxic depending on dose.', 3, 'standard', 'pending'),
(194, ARRAY['Logical'], ARRAY['Essential / definitive'], 'LD50 refers to the dose of a substance that is:', '[{"id":"a","text":"Lethal to 50% of a test population"}, {"id":"b","text":"Effective in 50% of a test population"}, {"id":"c","text":"Non-toxic to all subjects"}, {"id":"d","text":"Half the maximum tolerated dose"}]'::jsonb, 'a', '[PENDING REVIEW] LD50 (median lethal dose) is the dose required to kill 50% of a tested population, a standard measure of acute toxicity.', 2, 'standard', 'pending'),
(194, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The branch of toxicology concerned with the effects of toxic substances on ecosystems is called:', '[{"id":"a","text":"Ecotoxicology"}, {"id":"b","text":"Forensic toxicology"}, {"id":"c","text":"Clinical toxicology"}, {"id":"d","text":"Occupational toxicology"}]'::jsonb, 'a', '[PENDING REVIEW] Ecotoxicology studies the effects of toxicants on populations and ecosystems, not just individual organisms.', 2, 'standard', 'pending'),
(194, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The capacity of a substance to cause cancer is referred to as its:', '[{"id":"a","text":"Carcinogenicity"}, {"id":"b","text":"Mutagenicity"}, {"id":"c","text":"Teratogenicity"}, {"id":"d","text":"Neurotoxicity"}]'::jsonb, 'a', '[PENDING REVIEW] Carcinogenicity describes a substance''s potential to cause cancer.', 2, 'standard', 'pending'),
(194, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The liver''s primary toxicological role is:', '[{"id":"a","text":"Filtration of solid waste"}, {"id":"b","text":"Detoxification and biotransformation of xenobiotics"}, {"id":"c","text":"Storage of toxins indefinitely"}, {"id":"d","text":"Production of red blood cells"}]'::jsonb, 'b', '[PENDING REVIEW] The liver is the primary site of xenobiotic biotransformation, converting foreign substances into forms that can be excreted.', 2, 'standard', 'pending'),
(194, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Bioaccumulation refers to:', '[{"id":"a","text":"The rapid excretion of a substance from an organism"}, {"id":"b","text":"The buildup of a substance in an organism faster than it can be eliminated"}, {"id":"c","text":"The breakdown of a substance into harmless byproducts"}, {"id":"d","text":"The dilution of a substance across a population"}]'::jsonb, 'b', '[PENDING REVIEW] Bioaccumulation occurs when an organism absorbs a substance at a rate faster than it is metabolized or excreted, leading to a buildup over time.', 2, 'standard', 'pending'),
(194, ARRAY['Logical'], ARRAY['Essential / definitive'], 'Acute toxicity refers to adverse effects that occur:', '[{"id":"a","text":"Only after decades of exposure"}, {"id":"b","text":"Within a short period after a single or short-term exposure"}, {"id":"c","text":"Exclusively in aquatic organisms"}, {"id":"d","text":"Only at sub-threshold doses"}]'::jsonb, 'b', '[PENDING REVIEW] Acute toxicity describes adverse effects arising shortly after a single or short-duration exposure to a substance.', 2, 'standard', 'pending'),
(194, ARRAY['Logical'], ARRAY['Essential / definitive'], 'The highest dose at which no observable adverse effect occurs is termed the:', '[{"id":"a","text":"LD50"}, {"id":"b","text":"No Observed Effect Level (NOEL)"}, {"id":"c","text":"Median effective dose"}, {"id":"d","text":"Threshold limit value"}]'::jsonb, 'b', '[PENDING REVIEW] The No Observed Effect Level (NOEL) is the highest tested dose at which no adverse effect is detected in a study population.', 3, 'standard', 'pending');
