-- 20 clearly-marked test fixture questions for BCH101 (course_id 8,
-- see cgpa_dev_seed_test_content.sql), spread across all 25
-- cognitive_pattern x information_type combos so the adaptive
-- weighting (mastery.ts/select.ts) has real, varied data to weight
-- against while building/testing the exam UI. Every prompt is
-- prefixed [TEST FIXTURE] and generic on purpose -- this is testing
-- the pipeline, not real Biochemistry content, and should never be
-- mistaken for authored curriculum material.
insert into cgpa.keystone_questions (course_id, cognitive_patterns, information_types, prompt, options, correct_option_id, explanation, difficulty, source, approval_status)
values
(8, array['Pragmatic'], array['Essential / definitive'], '[TEST FIXTURE] Q1 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'a', 'Test fixture explanation.', 2, 'standard', 'approved'),
(8, array['Pragmatic'], array['Contextual / rhetoric'], '[TEST FIXTURE] Q2 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'b', 'Test fixture explanation.', 2, 'standard', 'approved'),
(8, array['Logical'], array['Essential / definitive'], '[TEST FIXTURE] Q3 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'c', 'Test fixture explanation.', 3, 'standard', 'approved'),
(8, array['Logical'], array['Procedural / supply chain'], '[TEST FIXTURE] Q4 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'a', 'Test fixture explanation.', 3, 'standard', 'approved'),
(8, array['Canon / Administrative'], array['Essential / definitive'], '[TEST FIXTURE] Q5 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'd', 'Test fixture explanation.', 1, 'standard', 'approved'),
(8, array['Canon / Administrative'], array['Abstract / Visual'], '[TEST FIXTURE] Q6 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'b', 'Test fixture explanation.', 2, 'standard', 'approved'),
(8, array['Statistical / Predictive'], array['Mathematical Proofs'], '[TEST FIXTURE] Q7 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'c', 'Test fixture explanation.', 4, 'standard', 'approved'),
(8, array['Statistical / Predictive'], array['Essential / definitive'], '[TEST FIXTURE] Q8 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'a', 'Test fixture explanation.', 3, 'standard', 'approved'),
(8, array['Pure Mathematical'], array['Mathematical Proofs'], '[TEST FIXTURE] Q9 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'd', 'Test fixture explanation.', 5, 'standard', 'approved'),
(8, array['Pure Mathematical'], array['Procedural / supply chain'], '[TEST FIXTURE] Q10 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'b', 'Test fixture explanation.', 4, 'standard', 'approved'),
(8, array['Pragmatic'], array['Procedural / supply chain'], '[TEST FIXTURE] Q11 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'a', 'Test fixture explanation.', 2, 'standard', 'approved'),
(8, array['Logical'], array['Abstract / Visual'], '[TEST FIXTURE] Q12 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'c', 'Test fixture explanation.', 3, 'standard', 'approved'),
(8, array['Canon / Administrative'], array['Contextual / rhetoric'], '[TEST FIXTURE] Q13 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'b', 'Test fixture explanation.', 1, 'standard', 'approved'),
(8, array['Statistical / Predictive'], array['Abstract / Visual'], '[TEST FIXTURE] Q14 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'd', 'Test fixture explanation.', 3, 'standard', 'approved'),
(8, array['Pure Mathematical'], array['Essential / definitive'], '[TEST FIXTURE] Q15 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'a', 'Test fixture explanation.', 4, 'standard', 'approved'),
(8, array['Pragmatic'], array['Abstract / Visual'], '[TEST FIXTURE] Q16 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'c', 'Test fixture explanation.', 2, 'standard', 'approved'),
(8, array['Logical'], array['Contextual / rhetoric'], '[TEST FIXTURE] Q17 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'b', 'Test fixture explanation.', 3, 'standard', 'approved'),
(8, array['Canon / Administrative'], array['Mathematical Proofs'], '[TEST FIXTURE] Q18 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'd', 'Test fixture explanation.', 4, 'standard', 'approved'),
(8, array['Statistical / Predictive'], array['Procedural / supply chain'], '[TEST FIXTURE] Q19 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'a', 'Test fixture explanation.', 2, 'standard', 'approved'),
(8, array['Pure Mathematical'], array['Contextual / rhetoric'], '[TEST FIXTURE] Q20 -- structural pipeline test, not real course content.', '[{"id":"a","text":"Option A"},{"id":"b","text":"Option B"},{"id":"c","text":"Option C"},{"id":"d","text":"Option D"}]'::jsonb, 'b', 'Test fixture explanation.', 3, 'standard', 'approved');
