-- Course catalog for Medicine (MBBS/Human Medicine), Pharmacy,
-- Nursing, all 7 Engineering disciplines, Law, and General Studies
-- (GST/GSS) -- "the only ones we need to provide before students
-- upload custom/proprietary course material anyway," per the
-- founder's own framing. 180 rows: a representative bootstrap
-- curriculum skeleton (3-4 courses per year per programme), not a
-- claim to a complete, institution-verified transcript -- that's
-- exactly what the custom-upload path (already built, routes to
-- WhatsApp) exists to fill in per-student/per-school.
--
-- GST/GSS: real numbering and exact titles vary meaningfully by
-- Nigerian institution (checked before writing this, not assumed) --
-- what's here (GST101-104, GST201, GST301) is the well-corroborated
-- common core (Use of English I/II, Nigerian Peoples and Culture,
-- Logic/Philosophy, and the CCMAS-2023-confirmed entrepreneurship
-- emphasis via Venture Creation and Entrepreneurship), not one
-- single universal code set claimed as definitive.
--
-- Engineering: years 1-2 are the same standard core duplicated across
-- all 7 disciplines' own department rows (the schema has no
-- cross-department shared-course mechanism yet, so exact duplication
-- is the honest choice here, not a workaround pretending otherwise);
-- years 3-5 diverge per discipline into real, discipline-specific
-- coursework.
insert into cgpa.courses (department_id, year, name, code, kind, approval_status)
select d.id, v.year, v.name, v.code, v.kind, 'approved'
from (values
  ('general-studies', 'general-studies', 1, 'Use of English and Communication Skills I', 'GST101', 'core'),
  ('general-studies', 'general-studies', 1, 'Use of English and Communication Skills II', 'GST102', 'core'),
  ('general-studies', 'general-studies', 1, 'Nigerian Peoples and Culture', 'GST103', 'core'),
  ('general-studies', 'general-studies', 1, 'Logic, Philosophy and Human Existence', 'GST104', 'core'),
  ('general-studies', 'general-studies', 2, 'Venture Creation and Entrepreneurship I', 'GST201', 'core'),
  ('general-studies', 'general-studies', 3, 'Peace and Conflict Resolution', 'GST301', 'core'),
  ('medicine', 'human-medicine', 1, 'Anatomy I', NULL, 'core'),
  ('medicine', 'human-medicine', 1, 'Physiology I', NULL, 'core'),
  ('medicine', 'human-medicine', 1, 'Biochemistry I', NULL, 'core'),
  ('medicine', 'human-medicine', 1, 'Behavioural Sciences in Medicine', NULL, 'core'),
  ('medicine', 'human-medicine', 2, 'Anatomy II (Histology and Embryology)', NULL, 'core'),
  ('medicine', 'human-medicine', 2, 'Physiology II', NULL, 'core'),
  ('medicine', 'human-medicine', 2, 'Biochemistry II', NULL, 'core'),
  ('medicine', 'human-medicine', 2, 'Introduction to Pharmacology', NULL, 'core'),
  ('medicine', 'human-medicine', 3, 'General Pathology', NULL, 'core'),
  ('medicine', 'human-medicine', 3, 'Medical Microbiology', NULL, 'core'),
  ('medicine', 'human-medicine', 3, 'Pharmacology', NULL, 'core'),
  ('medicine', 'human-medicine', 3, 'Community Health I', NULL, 'core'),
  ('medicine', 'human-medicine', 4, 'Introduction to Clinical Methods', NULL, 'core'),
  ('medicine', 'human-medicine', 4, 'Surgery I', NULL, 'core'),
  ('medicine', 'human-medicine', 4, 'Paediatrics I', NULL, 'core'),
  ('medicine', 'human-medicine', 4, 'Obstetrics and Gynaecology I', NULL, 'core'),
  ('medicine', 'human-medicine', 5, 'Internal Medicine II', NULL, 'core'),
  ('medicine', 'human-medicine', 5, 'Surgery II', NULL, 'core'),
  ('medicine', 'human-medicine', 5, 'Psychiatry', NULL, 'core'),
  ('medicine', 'human-medicine', 5, 'Community Health II', NULL, 'core'),
  ('medicine', 'human-medicine', 6, 'Internal Medicine III (Finals)', NULL, 'core'),
  ('medicine', 'human-medicine', 6, 'Surgery III (Finals)', NULL, 'core'),
  ('medicine', 'human-medicine', 6, 'Obstetrics and Gynaecology II', NULL, 'core'),
  ('medicine', 'human-medicine', 6, 'Paediatrics II', NULL, 'core'),
  ('pharmacy', 'pharmacy', 1, 'General Chemistry', NULL, 'core'),
  ('pharmacy', 'pharmacy', 1, 'General Physics', NULL, 'core'),
  ('pharmacy', 'pharmacy', 1, 'General Biology', NULL, 'core'),
  ('pharmacy', 'pharmacy', 2, 'Organic Chemistry', NULL, 'core'),
  ('pharmacy', 'pharmacy', 2, 'Human Anatomy and Physiology', NULL, 'core'),
  ('pharmacy', 'pharmacy', 2, 'Pharmaceutical Microbiology', NULL, 'core'),
  ('pharmacy', 'pharmacy', 3, 'Pharmaceutics I', NULL, 'core'),
  ('pharmacy', 'pharmacy', 3, 'Pharmacology I', NULL, 'core'),
  ('pharmacy', 'pharmacy', 3, 'Pharmacognosy I', NULL, 'core'),
  ('pharmacy', 'pharmacy', 4, 'Pharmaceutics II', NULL, 'core'),
  ('pharmacy', 'pharmacy', 4, 'Pharmacology II', NULL, 'core'),
  ('pharmacy', 'pharmacy', 4, 'Clinical Pharmacy I', NULL, 'core'),
  ('pharmacy', 'pharmacy', 5, 'Industrial Pharmacy', NULL, 'core'),
  ('pharmacy', 'pharmacy', 5, 'Clinical Pharmacy II', NULL, 'core'),
  ('pharmacy', 'pharmacy', 5, 'Pharmacy Practice and Law', NULL, 'core'),
  ('nursing', 'nursing-science', 1, 'Anatomy for Nursing', NULL, 'core'),
  ('nursing', 'nursing-science', 1, 'Physiology for Nursing', NULL, 'core'),
  ('nursing', 'nursing-science', 1, 'Nursing Foundations I', NULL, 'core'),
  ('nursing', 'nursing-science', 2, 'Pharmacology for Nurses', NULL, 'core'),
  ('nursing', 'nursing-science', 2, 'Medical-Surgical Nursing I', NULL, 'core'),
  ('nursing', 'nursing-science', 2, 'Nutrition and Dietetics', NULL, 'core'),
  ('nursing', 'nursing-science', 3, 'Medical-Surgical Nursing II', NULL, 'core'),
  ('nursing', 'nursing-science', 3, 'Maternal and Child Health Nursing', NULL, 'core'),
  ('nursing', 'nursing-science', 3, 'Community Health Nursing I', NULL, 'core'),
  ('nursing', 'nursing-science', 4, 'Mental Health and Psychiatric Nursing', NULL, 'core'),
  ('nursing', 'nursing-science', 4, 'Paediatric Nursing', NULL, 'core'),
  ('nursing', 'nursing-science', 4, 'Nursing Research', NULL, 'core'),
  ('nursing', 'nursing-science', 5, 'Nursing Management and Leadership', NULL, 'core'),
  ('nursing', 'nursing-science', 5, 'Midwifery', NULL, 'core'),
  ('nursing', 'nursing-science', 5, 'Critical Care Nursing', NULL, 'core'),
  ('law', 'common-law', 1, 'Nigerian Legal System', NULL, 'core'),
  ('law', 'common-law', 1, 'Constitutional Law I', NULL, 'core'),
  ('law', 'common-law', 1, 'Law of Contract I', NULL, 'core'),
  ('law', 'common-law', 2, 'Law of Contract II', NULL, 'core'),
  ('law', 'common-law', 2, 'Law of Torts', NULL, 'core'),
  ('law', 'common-law', 2, 'Family Law', NULL, 'core'),
  ('law', 'common-law', 3, 'Criminal Law', NULL, 'core'),
  ('law', 'common-law', 3, 'Land Law', NULL, 'core'),
  ('law', 'common-law', 3, 'Law of Evidence', NULL, 'core'),
  ('law', 'common-law', 4, 'Company Law', NULL, 'core'),
  ('law', 'common-law', 4, 'Commercial Law', NULL, 'core'),
  ('law', 'common-law', 4, 'Law of Equity and Trusts', NULL, 'core'),
  ('law', 'common-law', 5, 'Legal Drafting and Conveyancing', NULL, 'core'),
  ('law', 'common-law', 5, 'International Law', NULL, 'core'),
  ('law', 'common-law', 5, 'Human Rights Law', NULL, 'core'),
  ('engineering', 'civil-engineering', 1, 'Engineering Mathematics I', NULL, 'core'),
  ('engineering', 'civil-engineering', 1, 'Engineering Drawing', NULL, 'core'),
  ('engineering', 'civil-engineering', 1, 'Introduction to Engineering', NULL, 'core'),
  ('engineering', 'civil-engineering', 2, 'Engineering Mathematics II', NULL, 'core'),
  ('engineering', 'civil-engineering', 2, 'Mechanics of Solids', NULL, 'core'),
  ('engineering', 'civil-engineering', 2, 'Thermodynamics', NULL, 'core'),
  ('engineering', 'civil-engineering', 3, 'Structural Analysis', NULL, 'core'),
  ('engineering', 'civil-engineering', 3, 'Soil Mechanics', NULL, 'core'),
  ('engineering', 'civil-engineering', 3, 'Hydraulics', NULL, 'core'),
  ('engineering', 'civil-engineering', 4, 'Reinforced Concrete Design', NULL, 'core'),
  ('engineering', 'civil-engineering', 4, 'Highway Engineering', NULL, 'core'),
  ('engineering', 'civil-engineering', 4, 'Water Resources Engineering', NULL, 'core'),
  ('engineering', 'civil-engineering', 5, 'Steel Structure Design', NULL, 'core'),
  ('engineering', 'civil-engineering', 5, 'Construction Management', NULL, 'core'),
  ('engineering', 'civil-engineering', 5, 'Final Year Project', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 1, 'Engineering Mathematics I', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 1, 'Engineering Drawing', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 1, 'Introduction to Engineering', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 2, 'Engineering Mathematics II', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 2, 'Mechanics of Solids', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 2, 'Thermodynamics', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 3, 'Fluid Mechanics', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 3, 'Machine Design I', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 3, 'Manufacturing Processes', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 4, 'Heat Transfer', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 4, 'Machine Design II', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 4, 'Control Systems', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 5, 'Automobile Engineering', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 5, 'Industrial Engineering', NULL, 'core'),
  ('engineering', 'mechanical-engineering', 5, 'Final Year Project', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 1, 'Engineering Mathematics I', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 1, 'Engineering Drawing', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 1, 'Introduction to Engineering', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 2, 'Engineering Mathematics II', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 2, 'Mechanics of Solids', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 2, 'Thermodynamics', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 3, 'Circuit Theory', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 3, 'Electronics I', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 3, 'Electrical Machines I', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 4, 'Power Systems I', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 4, 'Electronics II', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 4, 'Control Engineering', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 5, 'Power Systems II', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 5, 'Telecommunications Engineering', NULL, 'core'),
  ('engineering', 'electrical-and-electronic-engineering', 5, 'Final Year Project', NULL, 'core'),
  ('engineering', 'chemical-engineering', 1, 'Engineering Mathematics I', NULL, 'core'),
  ('engineering', 'chemical-engineering', 1, 'Engineering Drawing', NULL, 'core'),
  ('engineering', 'chemical-engineering', 1, 'Introduction to Engineering', NULL, 'core'),
  ('engineering', 'chemical-engineering', 2, 'Engineering Mathematics II', NULL, 'core'),
  ('engineering', 'chemical-engineering', 2, 'Mechanics of Solids', NULL, 'core'),
  ('engineering', 'chemical-engineering', 2, 'Thermodynamics', NULL, 'core'),
  ('engineering', 'chemical-engineering', 3, 'Mass Transfer Operations', NULL, 'core'),
  ('engineering', 'chemical-engineering', 3, 'Chemical Reaction Engineering', NULL, 'core'),
  ('engineering', 'chemical-engineering', 3, 'Process Fluid Mechanics', NULL, 'core'),
  ('engineering', 'chemical-engineering', 4, 'Process Control', NULL, 'core'),
  ('engineering', 'chemical-engineering', 4, 'Plant Design', NULL, 'core'),
  ('engineering', 'chemical-engineering', 4, 'Heat Transfer Operations', NULL, 'core'),
  ('engineering', 'chemical-engineering', 5, 'Process Economics', NULL, 'core'),
  ('engineering', 'chemical-engineering', 5, 'Petrochemical Engineering', NULL, 'core'),
  ('engineering', 'chemical-engineering', 5, 'Final Year Project', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 1, 'Engineering Mathematics I', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 1, 'Engineering Drawing', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 1, 'Introduction to Engineering', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 2, 'Engineering Mathematics II', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 2, 'Mechanics of Solids', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 2, 'Thermodynamics', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 3, 'Reservoir Engineering I', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 3, 'Drilling Engineering', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 3, 'Petroleum Geology', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 4, 'Reservoir Engineering II', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 4, 'Production Engineering', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 4, 'Well Logging', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 5, 'Natural Gas Engineering', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 5, 'Petroleum Economics', NULL, 'core'),
  ('engineering', 'petroleum-engineering', 5, 'Final Year Project', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 1, 'Engineering Mathematics I', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 1, 'Engineering Drawing', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 1, 'Introduction to Engineering', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 2, 'Engineering Mathematics II', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 2, 'Mechanics of Solids', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 2, 'Thermodynamics', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 3, 'Soil and Water Engineering', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 3, 'Farm Power and Machinery', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 3, 'Post-Harvest Engineering', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 4, 'Irrigation and Drainage Engineering', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 4, 'Food Process Engineering', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 4, 'Bioresources Engineering', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 5, 'Farm Structures', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 5, 'Renewable Energy in Agriculture', NULL, 'core'),
  ('engineering', 'agricultural-and-bioresources-engineering', 5, 'Final Year Project', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 1, 'Engineering Mathematics I', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 1, 'Engineering Drawing', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 1, 'Introduction to Engineering', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 2, 'Engineering Mathematics II', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 2, 'Mechanics of Solids', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 2, 'Thermodynamics', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 3, 'Physical Metallurgy', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 3, 'Mineral Processing', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 3, 'Materials Science', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 4, 'Extractive Metallurgy', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 4, 'Corrosion Engineering', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 4, 'Ceramic Materials', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 5, 'Polymer Engineering', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 5, 'Metal Casting and Welding', NULL, 'core'),
  ('engineering', 'metallurgical-and-materials-engineering', 5, 'Final Year Project', NULL, 'core')
) as v(faculty_slug, dept_slug, year, name, code, kind)
join cgpa.faculties f on f.slug = v.faculty_slug
join cgpa.departments d on d.faculty_id = f.id and d.slug = v.dept_slug
on conflict do nothing;
